[[constraint]]
  name = "github.com/fatih/color"
  version = "1.5.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  # Temporary fork until https://github.com/urfave/cli/pull/735 is merged
  name = "github.com/urfave/cli"
  source = "github.com/rliebz/cli"
  branch = "combined"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  branch = "v2"
