defaults:
  # Common
  job_defaults: &job_defaults
    working_directory: /go/src/github.com/rliebz/tusk
    docker:
      - image: circleci/golang:1.10
    environment: &environment_defaults
      TEST_RESULTS: /tmp/test-results
  mktestdir: &mktestdir
    name: Create the test directory
    command: mkdir -p $TEST_RESULTS
  install_tusk: &install_tusk
    name: Install the application
    command: |
      go get -u github.com/golang/dep/cmd/dep
      dep ensure
      go install
  store_artifacts: &store_artifacts
    path: /tmp/test-results
    destination: raw-test-output
  store_test_results: &store_test_results
    path: /tmp/test-results

  # Lint
  install_lint_dependencies: &install_lint_dependencies
    name: Install linting dependencies
    command: |
      go get github.com/alecthomas/gometalinter
      gometalinter --install
  lint: &lint
    name: Run gometalinter
    command: tusk --quiet lint | tee $TEST_RESULTS/gometalinter.out

  # Test
  install_test_dependencies: &install_test_dependencies
    name: Install testing dependencies
    command: go get github.com/jstemmer/go-junit-report
  test: &test
    name: Run go test
    command: |
      trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
      tusk --quiet test --verbose --no-lint | tee $TEST_RESULTS/go-test.out

  # Release
  install_release_dependencies: &install_release_dependencies
    name: Install goreleaser dependencies
    command: |
      sudo apt-get -y install rpm
      curl -sL https://git.io/goreleaser > /tmp/goreleaser
      sudo chmod +x /tmp/goreleaser
      sudo mv /tmp/goreleaser /usr/local/bin
  release: &release
    name: Run goreleaser
    command: |
      # Pin goreleaser version
      export VERSION=v0.62.3
      sudo "PATH=$PATH" --preserve-env /go/bin/tusk release ${RELEASE_FLAGS}

version: 2
jobs:
  # For running tests locally
  build:
    <<: *job_defaults
    environment:
      <<: *environment_defaults
      RELEASE_FLAGS: --snapshot
    steps:
      - checkout
      - run: *mktestdir
      - run: *install_tusk
      - run: *install_lint_dependencies
      - run: *lint
      - run: *install_test_dependencies
      - run: *test
      # Local release is dry-run only
      - run: *install_release_dependencies
      - run: *release

  lint:
    <<: *job_defaults
    steps:
      - checkout
      - run: *mktestdir
      - run: *install_tusk
      - run: *install_lint_dependencies
      - run: *lint
      - store_artifacts: *store_artifacts
      - store_test_results: *store_test_results

  test:
    <<: *job_defaults
    steps:
      - checkout
      - run: *mktestdir
      - run: *install_tusk
      - run: *install_test_dependencies
      - run: *test
      - store_artifacts: *store_artifacts
      - store_test_results: *store_test_results

  release:
    <<: *job_defaults
    steps:
      - checkout
      - run: *install_tusk
      - run: *install_release_dependencies
      - deploy: *release

workflows:
  version: 2
  pipeline:
    jobs:
      - lint:
          filters:
            tags:
              only: /.*/
      - test:
          filters:
            tags:
              only: /.*/
      - release:
          requires:
            - lint
            - test
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
            branches:
              ignore: /.*/
