version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9

    working_directory: /go/src/github.com/rliebz/tusk

    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
      - checkout

      - run: mkdir -p $TEST_RESULTS

      - run:
          name: Install testing dependencies
          command: |
            go get github.com/jstemmer/go-junit-report
            go get github.com/alecthomas/gometalinter
            gometalinter --install

      - run:
          name: Install the application
          command: go install

      - run:
          name: Run gometalinter
          command: tusk -q lint | tee $TEST_RESULTS/gometalinter.out

      - run:
          name: Run go test
          command: |
            trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
            tusk -q test --verbose --lint=false | tee $TEST_RESULTS/go-test.out

      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output

      - store_test_results:
          path: /tmp/test-results

  release:
    docker:
      - image: circleci/golang:1.9

    working_directory: /go/src/github.com/rliebz/tusk

    steps:
      - checkout

      - run:
          name: Install fpm
          command: |
            sudo apt-get update
            sudo apt-get -y install ruby ruby-dev rubygems build-essential
            sudo gem install --no-ri --no-rdoc fpm

      - run:
          name: Run goreleaser
          command: curl -sL https://git.io/goreleaser | bash

workflows:
  version: 2
  build-and-release:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - release:
          requires:
            - build
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
            branches:
              ignore: /.*/
