version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/rliebz/tusk
    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS
      - run:
          name: Install dependencies
          command: go get -u github.com/alecthomas/gometalinter
      - run:
          name: Run gometalinter
          command: gometalinter --config .gometalinter.json ./... | tee ${TEST_RESULTS}/gometalinter.out
      - run:
          name: Run go test
          command: go test -v -cover ./... | tee ${TEST_RESULTS/go-test.out
      - store_test_results:
          path: /tmp/test-results

